# Generated by Django 5.1.4 on 2025-01-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='id',
            new_name='students_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='student_id',
        ),
    ]
