# Generated by Django 5.1.4 on 2025-01-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_school_students_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('levelid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
    ]
