# Generated by Django 5.1.4 on 2025-01-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_level_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='level',
        ),
    ]
