# Generated by Django 5.1.4 on 2025-01-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_id',
            new_name='students_id',
        ),
    ]
